// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/api/wholesale/save": {
    params: {};
  };
  "/api/products": {
    params: {};
  };
  "/api/requests": {
    params: {};
  };
  "/auth/login": {
    params: {};
  };
  "/webhooks": {
    params: {};
  };
  "/webhooks/app/scopes_update": {
    params: {};
  };
  "/webhooks/app/uninstalled": {
    params: {};
  };
  "/privacy": {
    params: {};
  };
  "/auth/*": {
    params: {
      "*": string;
    };
  };
  "/app": {
    params: {};
  };
  "/app/requests": {
    params: {};
  };
};

type RouteFiles = {
  "root.jsx": {
    id: "root";
    page: "/" | "/api/wholesale/save" | "/api/products" | "/api/requests" | "/auth/login" | "/webhooks" | "/webhooks/app/scopes_update" | "/webhooks/app/uninstalled" | "/privacy" | "/auth/*" | "/app" | "/app/requests";
  };
  "routes/api.wholesale.save.jsx": {
    id: "routes/api.wholesale.save";
    page: "/api/wholesale/save";
  };
  "routes/api.products.jsx": {
    id: "routes/api.products";
    page: "/api/products";
  };
  "routes/api.requests.jsx": {
    id: "routes/api.requests";
    page: "/api/requests";
  };
  "routes/auth.login/route.jsx": {
    id: "routes/auth.login";
    page: "/auth/login";
  };
  "routes/webhooks.jsx": {
    id: "routes/webhooks";
    page: "/webhooks" | "/webhooks/app/scopes_update" | "/webhooks/app/uninstalled";
  };
  "routes/webhooks.app.scopes_update.jsx": {
    id: "routes/webhooks.app.scopes_update";
    page: "/webhooks/app/scopes_update";
  };
  "routes/webhooks.app.uninstalled.jsx": {
    id: "routes/webhooks.app.uninstalled";
    page: "/webhooks/app/uninstalled";
  };
  "routes/privacy.jsx": {
    id: "routes/privacy";
    page: "/privacy";
  };
  "routes/_index/route.jsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/auth.$.jsx": {
    id: "routes/auth.$";
    page: "/auth/*";
  };
  "routes/app.jsx": {
    id: "routes/app";
    page: "/app" | "/app/requests";
  };
  "routes/app.requests.jsx": {
    id: "routes/app.requests";
    page: "/app/requests";
  };
  "routes/app._index.jsx": {
    id: "routes/app._index";
    page: "/app";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.jsx");
  "routes/api.wholesale.save": typeof import("./app/routes/api.wholesale.save.jsx");
  "routes/api.products": typeof import("./app/routes/api.products.jsx");
  "routes/api.requests": typeof import("./app/routes/api.requests.jsx");
  "routes/auth.login": typeof import("./app/routes/auth.login/route.jsx");
  "routes/webhooks": typeof import("./app/routes/webhooks.jsx");
  "routes/webhooks.app.scopes_update": typeof import("./app/routes/webhooks.app.scopes_update.jsx");
  "routes/webhooks.app.uninstalled": typeof import("./app/routes/webhooks.app.uninstalled.jsx");
  "routes/privacy": typeof import("./app/routes/privacy.jsx");
  "routes/_index": typeof import("./app/routes/_index/route.jsx");
  "routes/auth.$": typeof import("./app/routes/auth.$.jsx");
  "routes/app": typeof import("./app/routes/app.jsx");
  "routes/app.requests": typeof import("./app/routes/app.requests.jsx");
  "routes/app._index": typeof import("./app/routes/app._index.jsx");
};